#!/bin/sh

die () {
   echo "*** mkconfig: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
EOF

echo "#define YALS_OS \"`uname -srmn`\""
echo "#define YALS_COMPILED \"`date`\""
echo "#define YALS_RELEASED \"Mon Mar 29 04:24:00 PM EDT 2021\""
echo "#define YALS_VERSION \"03v\""
echo "#define YALS_ID \"771ace0e3f9a93df23331309be6e632b5cc2d298\""
